import Head from 'next/head'
import { Vector } from '@/components/index'

const RootLayout = ({children}: any) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col min-h-screen">
                <div className="container">
                    {children}
                </div>

                <footer className='mt-auto bg-orange-500 dark:bg-orang-800 w-full'>
                    <div className="grid grid-cols-3 gap-4  content-center h-12">
                        <div className='place-self-center'>
                            <h2>Develop By @codesyariah122</h2>
                        </div>
                        <div className="place-self-center">
                            Sitemap Link
                        </div>
                        <div className="place-self-center">
                            <Vector name='browser' width={30} height={30} />
                        </div>
                    </div>
                </footer>
            </main>

        </>
    )
}

export default RootLayout